version: '3.8'
services:
  app:
    build: .
    command: npm run start:dev
    image: backend
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=developmentW
